const USERS=[
{id:'U-DEMO-1',name:'Sol Demo',code:'2468',role:'Super Admin',superAdmin:true,sectors:['entrega_materiales','heridas']},
{id:'U-DEMO-2',name:'Diego Demo',code:'1357',role:'Operador',superAdmin:false,sectors:['entrega_materiales']},
{id:'U-DEMO-3',name:'Jorge Demo',code:'9876',role:'Operador',superAdmin:false,sectors:['entrega_materiales']}];
const SEED=[
{id:'ENT-001',remito:'18451',material:'Kit quirúrgico Demo A',cantidad:'1',destino:'Sanatorio Parque',paciente:'Juan Pérez',medico:'Dr. González',state:'assigned',assignedTo:'U-DEMO-1',createdAt:'2026-08-14T09:10:00'},
{id:'ENT-002',remito:'18452',material:'Material Demo B',cantidad:'2',destino:'Clínica del Centro',paciente:'María López',medico:'Dra. Romero',state:'out',assignedTo:'U-DEMO-2',exitBy:'Diego Demo',exitAt:'2026-08-14T10:20:00',createdAt:'2026-08-14T08:30:00'},
{id:'ENT-003',remito:'18453',material:'Set de curación Demo C',cantidad:'1',destino:'Hospital Italiano',paciente:'Carlos Díaz',medico:'Dr. Fernández',state:'assigned',assignedTo:'U-DEMO-2',createdAt:'2026-08-14T11:00:00'},
{id:'ENT-004',remito:'18449',material:'Kit quirúrgico Demo A',cantidad:'1',destino:'Sanatorio Parque',paciente:'Ana Suárez',medico:'Dr. González',state:'done',assignedTo:'U-DEMO-3',exitBy:'Jorge Demo',deliveredBy:'Jorge Demo',receivedBy:'Laura Mesa',deliveredAt:'2026-08-13T16:15:00',createdAt:'2026-08-13T10:00:00'}];
let session=null,lastSync=null,tasks=[],currentTask=null,manageAll=false; const $=x=>document.getElementById(x);
function fmt(v){return v?new Intl.DateTimeFormat('es-AR',{dateStyle:'short',timeStyle:'short'}).format(new Date(v)):'—'} function userName(id){return USERS.find(u=>u.id===id)?.name||id}
async function init(){if('serviceWorker'in navigator){try{const reg=await navigator.serviceWorker.register('./service-worker.js');reg.addEventListener('updatefound',()=>{const nw=reg.installing;nw.addEventListener('statechange',()=>{if(nw.state==='installed'&&navigator.serviceWorker.controller)$('updateToast').classList.remove('hidden')})});navigator.serviceWorker.addEventListener('controllerchange',()=>location.reload())}catch(e){}}
USERS.forEach(u=>{let o=document.createElement('option');o.value=u.id;o.textContent=u.name;$('user').appendChild(o)}); session=await idbGet(STORES.kv,'session');lastSync=await idbGet(STORES.kv,'lastSync');tasks=await idbGet(STORES.kv,'demoTasksV3')||SEED;$('activate').onclick=activate;$('sync').onclick=sync;$('logout').onclick=logout;$('remito').onchange=previewPhoto;$('confirmDelivery').onclick=confirmDelivery;$('recordSearch').oninput=renderRecords;$('recordState').onchange=renderRecords;$('recordUser').onchange=renderRecords;$('newForm').onsubmit=createDelivery;$('updateNow').onclick=()=>navigator.serviceWorker.getRegistration().then(r=>{if(r?.waiting)r.waiting.postMessage({type:'SKIP_WAITING'});else location.reload()});document.querySelectorAll('.nav').forEach(n=>n.onclick=()=>show(n.dataset.go));window.addEventListener('online',()=>{status();sync()});window.addEventListener('offline',status);setTimeout(()=>{$('splash').classList.add('hidden');route()},600)}
function route(){if(session){$('activation').classList.add('hidden');$('shell').classList.remove('hidden');render();show('home')}else{$('activation').classList.remove('hidden');$('shell').classList.add('hidden')}}
async function activate(){let u=USERS.find(x=>x.id===$('user').value&&x.code===$('code').value.trim());if(!u){$('err').className='error';$('err').textContent='Usuario o código incorrecto.';return}session={...u,deviceId:crypto.randomUUID?crypto.randomUUID():'dev-'+Date.now(),activatedAt:new Date().toISOString()};await idbSet(STORES.kv,'session',session);route()}
async function logout(){if(confirm('¿Desvincular este dispositivo?')){await idbSet(STORES.kv,'session',null);session=null;route()}} async function sync(){if(session&&navigator.onLine){lastSync=new Date().toISOString();await idbSet(STORES.kv,'lastSync',lastSync)}status()}
function status(){if(!session)return;let on=navigator.onLine;$('conn').textContent=on?'Conectado':'Sin conexión';$('last').textContent=on?'Sincronizado · '+fmt(lastSync):'Offline · última sync '+fmt(lastSync);$('deviceStatus').textContent=on?'Conectado':'Sin conexión';$('deviceSync').textContent=fmt(lastSync)}
function render(){ $('hello').textContent=session.name.split(' ')[0];$('profileName').textContent=session.name;$('role').textContent=session.role;$('deviceId').textContent=session.deviceId.slice(0,10).toUpperCase();$('activatedAt').textContent=fmt(session.activatedAt);let m=$('modules');m.innerHTML='';if(session.sectors.includes('entrega_materiales'))m.innerHTML+=`<button class="module" onclick="show('materials')"><div class="module-icon">📦</div><div class="module-main"><strong>Control de Entrega<br>de Materiales</strong><small>Seguimiento operativo</small></div><div class="arrow">›</div></button>`;if(session.sectors.includes('heridas'))m.innerHTML+=`<button class="module green" onclick="show('wounds')"><div class="module-icon">🩹</div><div class="module-main"><strong>Cuidado de Heridas</strong><small>Próximamente</small></div><div class="arrow">›</div></button>`;$('adminAction').classList.toggle('hidden',!session.superAdmin);fillAssignees();renderAssigned();renderManage();renderRecords();status()}
function fillAssignees(){['newAssigned','recordUser'].forEach(id=>{let s=$(id);let first=id==='recordUser'?'<option value="">Todos los usuarios</option>':'';s.innerHTML=first+USERS.map(u=>`<option value="${u.id}">${u.name}</option>`).join('')})}
function stateLabel(s){return s==='assigned'?'Asignado':s==='out'?'Salida registrada':'Entregado'} function canAct(t){return session.superAdmin||t.assignedTo===session.userId}
function taskHTML(t){return `<div class="task-card"><div class="task-top"><div><div class="task-title">${t.material}</div><div class="task-meta">Remito #${t.remito} · ${t.destino}<br>Asignado a: ${userName(t.assignedTo)}</div></div><span class="state-pill ${t.state==='out'?'out':t.state==='done'?'done':''}">${stateLabel(t.state)}</span></div><div class="task-actions"><button class="secondary" onclick="openTask('${t.id}')">Ver detalle</button>${canAct(t)&&t.state==='assigned'?`<button class="primary" onclick="registerExit('${t.id}')">Registrar salida</button>`:canAct(t)&&t.state==='out'?`<button class="primary" onclick="openDelivery('${t.id}')">Registrar entrega</button>`:''}</div></div>`}
function renderAssigned(){let a=tasks.filter(t=>t.assignedTo===session.userId&&t.state!=='done');$('assignedList').innerHTML=a.length?a.map(taskHTML).join(''):'<div class="placeholder"><div class="placeholder-icon">✓</div><h2>Todo al día</h2><p>No tenés pendientes.</p></div>'}
function renderManage(){let list=session.superAdmin&&manageAll?tasks:tasks.filter(t=>t.assignedTo===session.userId);$('manageList').innerHTML=list.map(taskHTML).join('')||'<div class="notice">No hay entregas.</div>';$('allTab').classList.toggle('hidden',!session.superAdmin)} function setManage(all){manageAll=all;$('mineTab').classList.toggle('active',!all);$('allTab').classList.toggle('active',all);renderManage()}
function detailRows(t){return `<div class="detail-grid"><div class="detail-row"><small>N.º de remito</small><strong>${t.remito}</strong></div><div class="detail-row"><small>Material</small><strong>${t.material} · ${t.cantidad}</strong></div><div class="detail-row"><small>Sanatorio / Destino</small><strong>${t.destino}</strong></div><div class="detail-row"><small>Paciente</small><strong>${t.paciente}</strong></div><div class="detail-row"><small>Médico</small><strong>${t.medico}</strong></div><div class="detail-row"><small>Asignado a</small><strong>${userName(t.assignedTo)}</strong></div>${t.exitBy?`<div class="detail-row"><small>Salida registrada por</small><strong>${t.exitBy} · ${fmt(t.exitAt)}</strong></div>`:''}${t.deliveredBy?`<div class="detail-row"><small>Entregado por</small><strong>${t.deliveredBy} · ${fmt(t.deliveredAt)}</strong></div>`:''}${t.receivedBy?`<div class="detail-row"><small>Recibió</small><strong>${t.receivedBy}</strong></div>`:''}</div>`}
function openTask(id){currentTask=tasks.find(t=>t.id===id);$('detailTitle').textContent='Remito #'+currentTask.remito;$('detailBody').innerHTML=detailRows(currentTask)+(canAct(currentTask)&&currentTask.state==='assigned'?`<button class="primary" style="margin-top:14px" onclick="registerExit('${id}')">REGISTRAR SALIDA</button>`:canAct(currentTask)&&currentTask.state==='out'?`<button class="primary" style="margin-top:14px" onclick="openDelivery('${id}')">REGISTRAR ENTREGA</button>`:'');show('detail')}
async function registerExit(id){let t=tasks.find(x=>x.id===id);if(!confirm('¿Confirmar salida?'))return;t.state='out';t.exitAt=new Date().toISOString();t.exitBy=session.name;await save();openTask(id)} function openDelivery(id){currentTask=tasks.find(t=>t.id===id);$('deliveryInfo').innerHTML=detailRows(currentTask);$('receivedBy').value='';$('notes').value='';$('remito').value='';$('preview').classList.add('hidden');show('delivery')}
function previewPhoto(e){let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{$('preview').src=r.result;$('preview').classList.remove('hidden')};r.readAsDataURL(f)} async function confirmDelivery(){let receiver=$('receivedBy').value.trim(),f=$('remito').files[0];if(!receiver)return alert('Ingresá quién recibe.');if(!f)return alert('La foto del remito es obligatoria.');let r=new FileReader();r.onload=async()=>{currentTask.state='done';currentTask.deliveredAt=new Date().toISOString();currentTask.deliveredBy=session.name;currentTask.receivedBy=receiver;currentTask.notes=$('notes').value;currentTask.remitoPhoto=r.result;await save();alert('Entrega registrada.');show('assigned')};r.readAsDataURL(f)}
async function createDelivery(e){e.preventDefault();let t={id:'ENT-'+Date.now(),remito:$('newRemito').value.trim(),material:$('newMaterial').value.trim(),cantidad:$('newQty').value||'1',destino:$('newDestino').value.trim(),paciente:$('newPaciente').value.trim(),medico:$('newMedico').value.trim(),assignedTo:$('newAssigned').value,state:'assigned',createdAt:new Date().toISOString(),createdBy:session.name};tasks.unshift(t);await save();e.target.reset();alert('Entrega creada y asignada.');show('manage')}
async function save(){await idbSet(STORES.kv,'demoTasksV3',tasks);renderAssigned();renderManage();renderRecords()}
function renderRecords(){if(!session?.superAdmin)return;let q=($('recordSearch')?.value||'').toLowerCase().trim(),st=$('recordState')?.value||'',u=$('recordUser')?.value||'';let r=tasks.filter(t=>(!st||t.state===st)&&(!u||t.assignedTo===u)&&(!q||[t.remito,t.destino,t.material,t.medico,t.paciente].some(v=>(v||'').toLowerCase().includes(q))));$('recordList').innerHTML=r.map(t=>`<div class="record" onclick="openTask('${t.id}')"><div class="task-top"><strong>Remito #${t.remito}</strong><span class="state-pill ${t.state==='done'?'done':t.state==='out'?'out':''}">${stateLabel(t.state)}</span></div><small>${t.destino} · ${t.material}<br>${t.medico} · ${t.paciente}<br>Asignado a ${userName(t.assignedTo)}${t.deliveredBy?' · Entregado por '+t.deliveredBy:''}</small></div>`).join('')||'<div class="notice">No encontramos registros con esos filtros.</div>'}
function show(name){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(name).classList.add('active');document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.go===name));if(name==='assigned')renderAssigned();if(name==='manage')renderManage();if(name==='records')renderRecords()}
document.addEventListener('DOMContentLoaded',init);